
import React from 'react';


const C: React.FC = () => {
  
  return (
    <div>
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA

      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA

      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
      DSAAAAAAAAAAAAAAAAAAAAAAA
    </div>
  );
};

export default C;